TechLinkIntranet/Models/Chart/PopulationDataAccessaLayer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TechLinkIntranet.Models.Chart
{
    public class PopulationDataAccessaLayer
    {
        public static List<PopulationModel> GetCityPopulationList()
        {
            var list = new List<PopulationModel>();
            list.Add(new PopulationModel { CityName = "PURI", PopulationYear2020 = 28000, PopulationYear2010 = 45000, PopulationYear2000 = 22000, PopulationYear1990 = 50000 });
            list.Add(new PopulationModel { CityName = "Bhubaneswar", PopulationYear2020 = 30000, PopulationYear2010 = 49000, PopulationYear2000 = 24000, PopulationYear1990 = 39000 });
            list.Add(new PopulationModel { CityName = "Cuttack", PopulationYear2020 = 35000, PopulationYear2010 = 56000, PopulationYear2000 = 26000, PopulationYear1990 = 41000 });
            list.Add(new PopulationModel { CityName = "Berhampur", PopulationYear2020 = 37000, PopulationYear2010 = 44000, PopulationYear2000 = 28000, PopulationYear1990 = 48000 });
            list.Add(new PopulationModel { CityName = "Odisha", PopulationYear2020 = 40000, PopulationYear2010 = 38000, PopulationYear2000 = 30000, PopulationYear1990 = 54000 });

            return list;

        }
    }
}

TechLinkIntranet/Models/Chart/PopulationModel  .cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TechLinkIntranet.Models.Chart
{
 
        public class PopulationModel
        {
            public string CityName { get; set; }
            public int PopulationYear2020 { get; set; }
            public int PopulationYear2010 { get; set; }
            public int PopulationYear2000 { get; set; }
            public int PopulationYear1990 { get; set; }

        }
   
}

TechLinkIntranet/Models/ModelIndex.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TechLinkIntranet.Models
{
    public class ModelIndex
    {
    }
}

TechLinkIntranet/Models/Test/TableItems.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TechLinkIntranet.Models.Test
{
    public class TableItems
    {
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Position { get; set; }
             

    }
}

TechLinkIntranet/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TechLinkIntranet.Models.Chart;

namespace TechLinkIntranet.Controllers
{
    public class ChartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult PopulationChart()
        {
            var populationList = PopulationDataAccessaLayer.GetCityPopulationList();
            return Json(populationList);
        }
    }
}

TechLinkIntranet/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TechLinkIntranet.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TechLinkIntranet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TechLinkIntranet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TechLinkIntranet/Controllers/MQCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TechLinkIntranet.Controllers
{
    public class MQCController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TechLinkIntranet/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TechLinkIntranet.Controllers
{
    public class ReportController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TechLinkIntranet/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TechLinkIntranet.Models.Test;

namespace TechLinkIntranet.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Table()
        {
            List<TableItems> tableItems = new List<TableItems> { new TableItems
            {
                Name ="Tran Duc An",
                Position ="Staff",
                Address ="Dictrist 4",
                PhoneNumber ="093"
            }
              
            };
            tableItems.Add(new TableItems
            {
                Name = "Luu Hong THanh",
                Position = "Staff",
                Address = "Dictrist 4",
                PhoneNumber = "093"
            });
            tableItems.Add(new TableItems
            {
                Name = "Luu Ha Thu",
                Position = "Staff",
                Address = "Dictrist 4",
                PhoneNumber = "093"
            });



            return View(tableItems);
        }
    }
}

TechLinkIntranet/Views/Chart/Index.cshtml
@*https://www.c-sharpcorner.com/article/creating-charts-with-asp-net-core-mvc-using-google-chart-api-part-two/*@




<title>@ViewData["Title"] - Column Chart</title>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div"></div>
<script type="text/javascript">


    google.charts.load('current', {
        packages: ['corechart', 'bar']
    });
    google.charts.setOnLoadCallback(LoadData);

    function LoadData() {
        $.ajax({

            url: 'Chart/PopulationChart',
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function (data) {
                PopulationChart(data);
                return false;
            }
        });
        return false;
    }

    function PopulationChart(data) {
        var dataArray = [
            ['City', '2020 Population', '2010 Population', '2000 Population', '1990 Population']
        ];
        $.each(data, function (i, item) {
            dataArray.push([item.cityName, item.populationYear2020, item.populationYear2010, item.populationYear2000, item.populationYear1990]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Population of Largest Cities of Odisha ',
            chartArea: {
                width: '50%'
            },
            colors: ['#b0120a', '#7b1fa2', '#ffab91', '#d95f02'],
            hAxis: {
                title: 'City',
                minValue: 0
            },
            vAxis: {
                title: 'Total Population'
            }
        };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

        chart.draw(data, options);
        return false;
    }
</script>  

TechLinkIntranet/Views/Dashboard/Index.cshtml
cx

TechLinkIntranet/Views/Home/Index.cshtml
@*@{
    Layout = null;
}*@

    <h1>Index page</h1>

TechLinkIntranet/Views/MQC/Index.cshtml
@*@{
    Layout = null;
}*@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index MQC Report</title>
</head>
<body>
    <h1>Index MQC Report</h1>
</body>
</html>

TechLinkIntranet/Views/Report/Index.cshtml
@*@{
    Layout = null;
}*@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index Production Report</title>
</head>
<body>
    Index Production Report
</body>
</html>

TechLinkIntranet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TLIntranet</title>
    <link href="~/libs/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/libs/bootstrap/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/libs/Font/css/fontawesome.css" rel="stylesheet" />
    <link href="~/libs/Site/Site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>*@

    <script src="~/libs/jquery/jquery.min.js"></script>
    @RenderSection("Styles", required: false)

</head>
<body>
    @*<style>
        body {
            width: 100%;
            margin: auto;
            min-width: 600px;
            max-width: 2000px
        }
    </style>*@
    @*<nav class="navbar navbar-expand-lg bg-white text-primary">
        <div class="row">
            <div class="col">
                <img src="~/libs/Images/logo3.jpg" alt="Logo" style="width:300px;" />
            </div>
            <div class="col-4">
               TECH-LINK INTRANET
            </div>

        </div>*@


    @*</nav>*@
<div class="container-fluid">
    <div class="row">
        <div class="col-3"><img class="img-fluid" src="~/libs/Images/logo3.jpg" alt="Logo" style="width:200px;" /></div>
        <div class="col-7">
            <h1 class="text-center text-success fa-bold"> <b>TECH-LINK INTRANET</b></h1>
        </div>
        <div class="col-2 text-info fa fa-clock">
            
            <h5> @DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss")</h5>
        </div>
    </div>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

        <a class="navbar-brand text-white fas fa-home" href="#">
            <img class="img-fluid" src="~/libs/Images/logo3.jpg" alt="Logo" style="width:100px;" />
             
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <div class="dropdown">
                <button type="button" class="btn btn-success text-white dropdown-toggle fas fa-suitcase" data-toggle="dropdown">
                    MQC Report
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Hose's MQC Monitoring</a>
                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">MQC Report</a>
                    <a class="dropdown-item disabled" asp-area="" asp-controller="Home" asp-action="Index">MQC Analysis</a>
                </div>
            </div>
            <div class="dropdown">
                <button type="button" class="btn btn-success text-white dropdown-toggle fas fa-share" data-toggle="dropdown">
                    Production Report
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-area="" asp-controller="Production" asp-action="Backlog">Back-log Report</a>
                    <a class="dropdown-item" asp-area="" asp-controller="Production" asp-action="Reliability">Reliability Report</a>
                    <a class="dropdown-item disabled" asp-area="" asp-controller="Production" asp-action="Index">Production Analysis</a>
                </div>
            </div>
            <div class="dropdown">
                <button type="button" class="btn btn-success text-white dropdown-toggle fas fa-warehouse" data-toggle="dropdown">
                    Ware house
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-area="" asp-controller="Warehouse" asp-action="InStock">In-Stock</a>
                    <a class="dropdown-item" asp-area="" asp-controller="Warehouse" asp-action="OutStock">Out-Stock</a>
                    <a class="dropdown-item disabled" asp-area="" asp-controller="Warehouse" asp-action="FinishedGoods">Finished-Goods</a>
                </div>
            </div>
            <div class="dropdown">
                <button type="button" class="btn btn-success text-white dropdown-toggle fas fa-democrat" data-toggle="dropdown">
                    Test
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-area="" asp-controller="Test" asp-action="Table">Table</a>
                    <a class="dropdown-item" asp-area="" asp-controller="Chart" asp-action="Index">Dashboard</a>
                    <a class="dropdown-item disabled" asp-area="" asp-controller="Warehouse" asp-action="FinishedGoods">Finished-Goods</a>
                </div>
            </div>

        </div>
        <form class="form-inline" action="/action_page.php">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-success" type="submit">Search</button>
        </form>
    </nav>
</div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - TLIntranet</p>
        </footer>
    </div>

    <environment include="Development">

        <script src="~/libs/bootstrap/js/bootstrap.js"></script>
        <script src="~/libs/jquery/jquery.js"></script>

    </environment>


    @RenderSection("Scripts", required: false)
</body>
</html>

TechLinkIntranet/Views/Test/Table.cshtml
@*@{
    Layout = null;
}*@
@model List<TechLinkIntranet.Models.Test.TableItems>
<table class="table table-bordered table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                Name
            </th>
            <th>
                PhoneNumber
            </th>
            <th>
                Address
            </th>
            <th>
                Position
            </th>
        </tr>
       
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            if (i % 2 == 0)
            {
                <tr class="">
                    <td>@Model[i].Name</td>
                    <td>@Model[i].PhoneNumber</td>
                    <td>@Model[i].Address</td>
                    <td>@Model[i].Position</td>
                </tr>
            }
            else
            {
                <tr class="">
                    <td>@Model[i].Name</td>
                    <td>@Model[i].PhoneNumber</td>
                    <td>@Model[i].Address</td>
                    <td>@Model[i].Position</td>
                </tr>
            }
        }
    </tbody>
</table>